### ISSUE TITLE
First off all good job! Proposal: Integrate couchbase lite

### ISSUE THREAD

**Issue by frank-dspeed** [quarkiverse/quarkus-couchbase#8]
https://github.com/couchbase/couchbase-lite-C

as this is already using the couchbase nativ lib and couchbase lite does the same it would be a small step to create quarkus-couchbase-lite which is even more interesting as this would allow to host a local couchbase data store right next to the app and then later sync with the real cluster.

**Comment by raycardillo** [comment]
@frank-dspeed The embedded/mobile SDKs are quite a bit different than the server SDKs. We will pass this feature request along to that team.

**Comment by raycardillo** [comment]
Closing per previous comment. This request (and issue link) was shared with the relevant team.
