### ISSUE TITLE
Make the extension available in the registry

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-couchbase#96]
It would be great to see this extension available in http://code.quarkus.io, http://extensions.quarkus.io, and in the quarkus cli tools. This would improve discoverability (it's where many Quarkus developers look for extensions), and so bring more feedback. 

Inclusion in those tools isn't a statement about maturity; many tools listed have [preview](https://quarkus.io/extensions/?status=preview) or [experimental](https://quarkus.io/extensions/?status=experimental) status, for example.

The process to be listed is fairly simple; it needs a maven release, and then a PR to update a text file. The full process is listed here: https://hub.quarkiverse.io/checklist/#make-your-extension-available-in-the-tooling
Some of the other parts of that checklist might be interesting, too, such as publishing docs, and integrating with the ecosystem CI. 

One caveat about being listed in the tools is that I think .alpha version numbers are ignored (is that right, @gastaldi?)

**Comment by raycardillo** [comment]
@holly-cummins This is done, but I cannot close the issue, and neither can @programmatix 

We need a few other folks at Couchbase to have permissions on this repo to be able to maintain it. How do we get access to this? Graham said he doesn't have admin and cannot add them either.

At the least, we need myself (I'm Sr. Manager of the team) and @emilienbev to be able to do things like respond/close issues, add reviewers to PRs, etc. It would be best if @programmatix and I had slightly elevated privs to be able to help maintain the repo, etc.

**Comment by holly-cummins** [comment]
> @holly-cummins This is done, but I cannot close the issue, and neither can @programmatix
> 
> We need a few other folks at Couchbase to have permissions on this repo to be able to maintain it. How do we get access to this? Graham said he doesn't have admin and cannot add them either.
> 
> At the least, we need myself (I'm Sr. Manager of the team) and @emilienbev to be able to do things like respond/close issues, add reviewers to PRs, etc. It would be best if @programmatix and I had slightly elevated privs to be able to help maintain the repo, etc.

The general quarkiverse approach is that people who're maintaining extensions should definitely have lots of privileges on the extension repo. So then the next question is 'but why can't Graham give people permissions?' The answer there is that we have GitOps-ed all the things, so the process for adjusting repo settings is PRs against the https://github.com/quarkiverse/quarkiverse-devops repo. This is sort of implied [here](https://hub.quarkiverse.io/checklistfornewprojects/#requesting-a-new-repository), but it's not very explicit, so @gastaldi or I will update those docs with a FAQ about managing repo settings.

**Comment by holly-cummins** [comment]
I'd suggest that @programmatix submit a PR against https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-couchbase.tf#L29C1-L35C2 adding  @emilienbev and @raycardillo to the list of maintainers.

```
# Add users to the team
resource "github_team_membership" "quarkus_couchbase" {
  for_each = { for tm in ["programmatix"] : tm => tm }
  team_id  = github_team.quarkus_couchbase.id
  username = each.value
  role     = "maintainer"
}
```

**Comment by gastaldi** [comment]
I've created https://github.com/quarkiverse/quarkiverse-devops/pull/279 doing exactly what https://github.com/quarkiverse/quarkus-couchbase/issues/96#issuecomment-2371596410 mentions. After the PR is merged you two should be able to maintain this repository.

**Comment by raycardillo** [comment]
Great, thanks @gastaldi and @holly-cummins! We seem to be all set with permissions now and the `beta` version of the extension has been published to the registry in `preview` status. Within a month or so, we will be iterating on more integration (e.g., dev ui, readiness probe, etc).
