### ISSUE TITLE
Could not find in maven

### ISSUE THREAD

**Issue by ultimate-raman** [quarkiverse/quarkus-couchbase#99]
Could not find artifact io.quarkiverse.couchbase:quarkus-couchbase:pom:1.0.0-alpha.1 in central (https://repo.maven.apache.org/maven2)

Getting this above issue when I add
        <dependency>
            <groupId>io.quarkiverse.couchbase</groupId>
            <artifactId>quarkus-couchbase</artifactId>
            <version>1.0.0-alpha.1</version>
        </dependency>
in pom.xml

**Comment by raycardillo** [comment]
`1.0.0-beta1` was just recently released. You can now find it in Maven:
https://central.sonatype.com/artifact/io.quarkiverse.couchbase/quarkus-couchbase?smo=true
